merchant1 = Merchant.create(name: "Mr. Moonstone Skull's Emporium", address: "7131 Mitchell Views", city: "New Frank", state: "Kansas", zip: 53851)
merchant2 = Merchant.create( name: "Kang's Thangs", address: "92687 Kirlin Curve", city: "East Ariel", state: "Florida", zip: 12843)

item1 = Item.create(name: "Ergonomic Granite Knife", description: "Chuck Norris compresses his files by doing a flying round house kick to the hard drive.", price: 72, image: "https://avatarfiles.alphacoders.com/125/thumb-125254.png", inventory: 10, merchant: merchant1)
item2 = Item.create( name: "Fantastic Linen Computer", description: "When Chuck Norris points to null,null quakes in fear.", price: 70, image: "https://avatarfiles.alphacoders.com/133/thumb-1335.jpg", inventory: 10, merchant: merchant1)
item3 = Item.create(name: "Mediocre Concrete Wallet", description: "Chuck Norris finished World of Warcraft.", price: 61, image: "https://avatarfiles.alphacoders.com/118/thumb-118200.jpg", inventory: 10, merchant: merchant1)
item4 = Item.create(name: "Intelligent Concrete Computer", description: "Chuck Norris doesn't pair program.", price: 15, image: "https://avatarfiles.alphacoders.com/165/thumb-165967.jpg", inventory: 10, merchant: merchant1)
item5 = Item.create(name: "Practical Plastic Shoes", description: "Chuck Norris breaks RSA 128-bit encrypted codes in milliseconds.", price: 56, image: "https://avatarfiles.alphacoders.com/160/thumb-160298.png", inventory: 10, merchant: merchant1)

item6 = Item.create(name: "Ergonomic Cotton Wallet", description: "Chuck Norris can access private methods.", price: 57, image: "https://avatarfiles.alphacoders.com/131/thumb-131127.jpg", inventory: 5, merchant: merchant1)
item7 = Item.create(name: "Heavy Duty Steel Chair", description: "Chuck Norris doesn't use a computer because a computer does everything slower than Chuck Norris.", price: 56, image: "https://avatarfiles.alphacoders.com/152/thumb-152177.jpg", inventory: 5, merchant: merchant1)
item8 = Item.create(name: "Practical Iron Gloves", description: "Chuck Norris knows the last digit of PI.", price: 43, image: "https://avatarfiles.alphacoders.com/120/thumb-120733.jpg", inventory: 5, merchant: merchant1)
item9 = Item.create(name: "Incredible Cotton Bag", description: "Chuck Norris can access private methods.", price: 68, image: "https://avatarfiles.alphacoders.com/232/thumb-232271.jpg", inventory: 5, merchant: merchant1)
item10 = Item.create(name: "Enormous Plastic Bag", description: "Chuck Norris solved the Travelling Salesman problem in O(1) time.", price: 19, image: "https://avatarfiles.alphacoders.com/223/thumb-223913.jpg", inventory: 5, merchant: merchant1)

item11 = Item.create(name: "Incredible Silk Wallet", description: "Chuck Norris doesn't have performance bottlenecks. He just makes the universe wait its turn.", price: 16, image: "https://avatarfiles.alphacoders.com/206/thumb-206020.jpg", inventory: 10, merchant: merchant2)
item12 = Item.create(name: "Awesome Linen Lamp", description: "Chuck Norris does not use revision control software. None of his code has ever needed revision.", price: 70, image: "https://avatarfiles.alphacoders.com/199/thumb-199362.jpg", inventory: 10, merchant: merchant2)
item13 = Item.create(name: "Ergonomic Granite Table", description: "The only pattern Chuck Norris knows is God Object.", price: 86, image: "https://avatarfiles.alphacoders.com/193/thumb-193772.jpg", inventory: 10, merchant: merchant2)
item14 = Item.create(name: "Ergonomic Leather Shirt", description: "Chuck Norris can binary search unsorted data.", price: 25, image: "https://avatarfiles.alphacoders.com/177/thumb-177871.jpg", inventory: 10, merchant: merchant2)
item15 = Item.create(name: "Heavy Duty Silk Watch", description: "Chuck Norris breaks RSA 128-bit encrypted codes in milliseconds.", price: 82, image: "https://avatarfiles.alphacoders.com/165/thumb-165968.jpg", inventory: 10, merchant: merchant2)

item16 = Item.create(name: "Sleek Copper Coat", description: "Chuck Norris doesn't get compiler errors,the language changes itself to accommodate Chuck Norris.", price: 36, image: "https://avatarfiles.alphacoders.com/657/thumb-65717.jpg", inventory: 5, merchant: merchant2)
item17 = Item.create(name: "Rustic Concrete Clock", description: "Chuck Norris can binary search unsorted data.", price: 86, image: "https://avatarfiles.alphacoders.com/391/thumb-39145.jpg", inventory: 5, merchant: merchant2)
item18 = Item.create(name: "Fantastic Marble Lamp", description: "Chuck Norris doesn't program with a keyboard. He stares the computer down until it does what he wants.", price: 21, image: "https://avatarfiles.alphacoders.com/386/thumb-38600.jpg", inventory: 5, merchant: merchant2)
item19 = Item.create(name: "Aerodynamic Plastic Keyboard", description: "Chuck Norris finished World of Warcraft.", price: 48, image: "https://avatarfiles.alphacoders.com/362/thumb-36221.jpg", inventory: 5, merchant: merchant2)
item20 = Item.create(name: "Durable Linen Shirt", description: "Chuck Norris finished World of Warcraft.", price: 5, image: "https://avatarfiles.alphacoders.com/362/thumb-36220.jpg", inventory: 5, merchant: merchant2)

regular_user = User.create(name: "Regular User", address: "1234 Regular St", city: "Regular City", state: "Regular State", zip: "00000", email: "user@example.com", password: "password_regular")
merchant_employee1 = User.create(name: "Mr. Moonstone Skull", address: "1234 Merchant St", city: "Merchant City", state: "Merchant State", zip: "00001", email: "merchant@example.com", password: "password_merchant", role: 1, merchant: merchant1)
merchant_employee2 = User.create(name: "General Kang", address: "4321 Merchant St", city: "Merchant City", state: "Merchant State", zip: "00001", email: "merchant2@example.com", password: "password_merchant", role: 1, merchant: merchant2)
admin_user = User.create(name: "Admin User", address: "1234 Admin St", city: "Admin City", state: "Admin State", zip: "00002", email: "admin@example.com", password: "password_admin", role: 2)

order1 = Order.create(user_id: regular_user.id)
order2 = Order.create(user_id: regular_user.id)
order3 = Order.create(user_id: regular_user.id)
order4 = Order.create(user_id: merchant_employee1.id)
order5 = Order.create(user_id: merchant_employee2.id)

order_item1_1 = OrderItem.create(price: item1.price, quantity: 2, item: item1, order: order1)
order_item1_2 = OrderItem.create(price: item2.price, quantity: 1, item: item2, order: order1)
order_item2_1 = OrderItem.create(price: item3.price, quantity: 2, item: item3, order: order2)
order_item2_2 = OrderItem.create(price: item4.price, quantity: 3, item: item4, order: order2)
order_item3_1 = OrderItem.create(price: item5.price, quantity: 2, item: item5, order: order3)
order_item3_2 = OrderItem.create(price: item6.price, quantity: 2, item: item6, order: order3)
order_item4_1 = OrderItem.create(price: item7.price, quantity: 1, item: item7, order: order4)
order_item4_2 = OrderItem.create(price: item8.price, quantity: 3, item: item8, order: order4)
order_item5_1 = OrderItem.create(price: item9.price, quantity: 2, item: item9, order: order5)
order_item5_2 = OrderItem.create(price: item10.price, quantity: 3, item: item10, order: order5)