merchant1 = Merchant.create(name: "Mr. Moonstone Skull's Emporium", address: "7131 Mitchell Views", city: "New Frank", state: "Kansas", zip: 53851)
merchant2 = Merchant.create( name: "Kang's Thangs", address: "92687 Kirlin Curve", city: "East Ariel", state: "Florida", zip: 12843)

merchant1_employee = User.create(name: "Mr. Moonstone Skull", address: "1234 Merchant St", city: "Merchant City", state: "Merchant State", zip: "00001", email: "merchant@example.com", password: "password_merchant", role: 1, merchant: merchant1)
merchant1.items.create(name: "Happy SpongeBob", description: "Chuck Norris compresses his files by doing a flying round house kick to the hard drive.", price: 10, image: "https://avatarfiles.alphacoders.com/125/thumb-125254.png", inventory: 50)
merchant1.items.create(name: "Drooly Patrick", description: "When Chuck Norris points to null,null quakes in fear.", price: 10, image: "https://avatarfiles.alphacoders.com/133/thumb-1335.jpg", inventory: 50)
merchant1.items.create(name: "Spotlight SpongeBob", description: "Chuck Norris finished World of Warcraft.", price: 10, image: "https://avatarfiles.alphacoders.com/118/thumb-118200.jpg", inventory: 50)
merchant1.items.create(name: "Unhappy Neighbor", description: "Chuck Norris doesn't pair program.", price: 10, image: "https://avatarfiles.alphacoders.com/165/thumb-165967.jpg", inventory: 50)
merchant1.items.create(name: "Rainbow Magic SpongeBob", description: "Chuck Norris breaks RSA 128-bit encrypted codes in milliseconds.", price: 10, image: "https://avatarfiles.alphacoders.com/160/thumb-160298.png", inventory: 50)
merchant1_discount = merchant1.discounts.create(percent_off: 10, minimum_quantity: 20)

merchant2_employee = User.create(name: "General Kang", address: "4321 Merchant St", city: "Merchant City", state: "Merchant State", zip: "00001", email: "merchant2@example.com", password: "password_merchant", role: 1, merchant: merchant2)
merchant2.items.create(name: "Shiny Gary", description: "Chuck Norris can access private methods.", price: 10, image: "https://avatarfiles.alphacoders.com/131/thumb-131127.jpg", inventory: 50)
merchant2.items.create(name: "Cheeky SpongeBob", description: "Chuck Norris doesn't use a computer because a computer does everything slower than Chuck Norris.", price: 10, image: "https://avatarfiles.alphacoders.com/152/thumb-152177.jpg", inventory: 50)
merchant2.items.create(name: "Hooded Patrick", description: "Chuck Norris knows the last digit of PI.", price: 10, image: "https://avatarfiles.alphacoders.com/120/thumb-120733.jpg", inventory: 50)
merchant2.items.create(name: "Demented Squidward", description: "Chuck Norris can access private methods.", price: 10, image: "https://avatarfiles.alphacoders.com/232/thumb-232271.jpg", inventory: 50)
merchant2.items.create(name: "Unamused SpongeBob", description: "Chuck Norris solved the Travelling Salesman problem in O(1) time.", price: 10, image: "https://avatarfiles.alphacoders.com/223/thumb-223913.jpg", inventory: 50)
merchant2_discount = merchant2.discounts.create(percent_off: 20, minimum_quantity: 10)

regular_user = User.create(name: "Regular User", address: "1234 Regular St", city: "Regular City", state: "Regular State", zip: "00000", email: "user@example.com", password: "password_regular")
admin_user = User.create(name: "Admin User", address: "1234 Admin St", city: "Admin City", state: "Admin State", zip: "00002", email: "admin@example.com", password: "password_admin", role: 2)